# Intro To Numpy

In [2]:
import numpy as np

## DataTypes & Attributes

In [3]:
# numpy has type ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([
    [1, 2.0, 3.3],
    [4, 5, 6.5]
])

a3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])

a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a3.shape

(2, 3, 3)

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a datafrom from numpy array

import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating numpy arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [20]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0, 100, size=(3, 5))
random_array

array([[49,  3, 65, 57, 95],
       [71, 51,  7, 25, 72],
       [16, 39, 37, 45, 45]])

In [24]:
random_array.size

15

In [25]:
random_array.shape

(3, 5)

In [26]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.21395289, 0.15092664, 0.55098103],
       [0.30084144, 0.57383406, 0.2924498 ],
       [0.60877322, 0.09319855, 0.68315067],
       [0.29937629, 0.2491057 , 0.81046786],
       [0.47168682, 0.56964479, 0.0467934 ]])

In [27]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.58301554, 0.13369938, 0.11729058],
       [0.1005951 , 0.50727206, 0.02732745],
       [0.75644051, 0.39939113, 0.25051476],
       [0.92926966, 0.84791661, 0.00525581],
       [0.94744103, 0.54205324, 0.91640757]])

In [31]:
# Pseudo-random numbers
np.random.seed(100)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[8, 8, 3],
       [7, 7, 0],
       [4, 2, 5],
       [2, 2, 2],
       [1, 0, 8]])

## 3. Viewing arrays and matrices