# Intro To Numpy

In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# numpy has type ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([
    [1, 2.0, 3.3],
    [4, 5, 6.5]
])

a3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])

a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a3.shape

(2, 3, 3)

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [11]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [13]:
# Create a datafrom from numpy array

import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating numpy arrays

In [14]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [15]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [19]:
random_array = np.random.randint(0, 100, size=(3, 5))
random_array

array([[60, 36, 26, 18, 62],
       [37, 27, 49, 78, 86],
       [40, 15, 76, 56, 36]])

In [20]:
random_array.size

15

In [21]:
random_array.shape

(3, 5)

In [22]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.38225292, 0.35287438, 0.27659952],
       [0.36009768, 0.77659455, 0.8818208 ],
       [0.75384268, 0.06667456, 0.35045008],
       [0.93829962, 0.58045787, 0.45179047],
       [0.53751595, 0.46035625, 0.8165975 ]])

In [23]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.75315307, 0.23986238, 0.73086595],
       [0.28481034, 0.94127399, 0.14524672],
       [0.47740857, 0.18277091, 0.74897007],
       [0.08579933, 0.13921914, 0.64531766],
       [0.0160182 , 0.77570211, 0.95074057]])

In [24]:
# Pseudo-random numbers
np.random.seed(100)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[8, 8, 3],
       [7, 7, 0],
       [4, 2, 5],
       [2, 2, 2],
       [1, 0, 8]])

## 3. Viewing arrays and matrices

In [25]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 7, 8])

In [26]:
a1

array([1, 2, 3])

In [27]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [28]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [29]:
a1[0]

1

In [30]:
a2[0]

array([1. , 2. , 3.3])

In [31]:
a2.shape

(2, 3)

In [32]:
a2[0].shape

(3,)

In [33]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
a3[0].shape

(3, 3)

In [35]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [36]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))

In [37]:
a4

array([[[[4, 0, 9, 6, 2],
         [4, 1, 5, 3, 4],
         [4, 3, 7, 1, 1],
         [7, 7, 0, 2, 9]],

        [[9, 3, 2, 5, 8],
         [1, 0, 7, 6, 2],
         [0, 8, 2, 5, 1],
         [8, 1, 5, 4, 2]],

        [[8, 3, 5, 0, 9],
         [3, 6, 3, 4, 7],
         [6, 3, 9, 0, 4],
         [4, 5, 7, 6, 6]]],


       [[[2, 4, 2, 7, 1],
         [6, 6, 0, 7, 2],
         [3, 5, 4, 2, 4],
         [3, 7, 9, 0, 0]],

        [[5, 9, 6, 6, 5],
         [6, 4, 7, 3, 9],
         [2, 3, 8, 7, 1],
         [5, 9, 3, 0, 6]],

        [[2, 3, 4, 8, 9],
         [8, 5, 2, 7, 5],
         [9, 0, 9, 8, 6],
         [2, 0, 5, 3, 2]]]])

In [38]:
# Get the first four numbers of inner most array in a4
a4[:, :, :, :4]

array([[[[4, 0, 9, 6],
         [4, 1, 5, 3],
         [4, 3, 7, 1],
         [7, 7, 0, 2]],

        [[9, 3, 2, 5],
         [1, 0, 7, 6],
         [0, 8, 2, 5],
         [8, 1, 5, 4]],

        [[8, 3, 5, 0],
         [3, 6, 3, 4],
         [6, 3, 9, 0],
         [4, 5, 7, 6]]],


       [[[2, 4, 2, 7],
         [6, 6, 0, 7],
         [3, 5, 4, 2],
         [3, 7, 9, 0]],

        [[5, 9, 6, 6],
         [6, 4, 7, 3],
         [2, 3, 8, 7],
         [5, 9, 3, 0]],

        [[2, 3, 4, 8],
         [8, 5, 2, 7],
         [9, 0, 9, 8],
         [2, 0, 5, 3]]]])

## 4. Manipulating & Comparing arrays

### Arithmetic

In [39]:
a1

array([1, 2, 3])

In [40]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
ones = np.ones(3)

In [42]:
a1 + ones

array([2., 3., 4.])

In [43]:
a1 - ones

array([0., 1., 2.])

In [44]:
a1 * ones

array([1., 2., 3.])

In [45]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [46]:
a1

array([1, 2, 3])

In [47]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [48]:
a2 * a1

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

### aggregation

In [49]:
listy = [1, 2, 3]
np.array(listy).sum()

6

In [50]:
np.sum(a2)

21.8

In [51]:
massive_array = np.random.random(100000)

In [52]:
massive_array[:10]

array([0.8596183 , 0.62532376, 0.98240783, 0.97650013, 0.16669413,
       0.02317814, 0.16074455, 0.92349683, 0.95354985, 0.21097842])

In [53]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

6.03 ms ± 208 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
29.5 µs ± 348 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [54]:
np.mean(a2)

3.6333333333333333

In [55]:
np.std(a2)

1.8226964152656422

In [56]:
np.var(a2)

3.3222222222222224

## Reshaping and Transposing

In [57]:
a2.shape

(2, 3)

In [58]:
a2.transpose().shape

(3, 2)

## 

In [59]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a2.reshape((2, 3, 1))

In [ ]:
a2.reshape((2, 3, 1)) * a3

In [ ]:
a3

In [ ]:
a2

In [ ]:
a2_reshaped = a2.reshape((2, 3, 1))

In [ ]:
a2_reshaped

In [ ]:
a2_reshaped.T

## Dot Product

In [ ]:
np.random.seed(10)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

mat1

In [ ]:
mat2

In [ ]:
mat1

In [ ]:
# Element wise multiplication
mat1 * mat2

In [ ]:
# Dot product
np.dot(mat1, mat2.T)

In [ ]:
np.random.seed(0)
sales_amount = np.random.randint(20, size=(5, 3))
weekly_sales = pd.DataFrame(sales_amount, index=["Mon", "Tue", "Wed", "Thu", "Fri"], columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [ ]:
weekly_sales

In [ ]:
prices = np.array([10, 8, 12])

In [ ]:
butter_prices = pd.DataFrame(prices.reshape(1, 3)
                                , index=["Prices"], columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [ ]:
butter_prices

In [ ]:
total_sales = prices.dot(sales_amount.T)

In [ ]:
total_sales

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [ ]:
daily_sales

## Comparison Operators

In [60]:
a1
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [61]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [62]:
a1 < a2

array([[False, False,  True],
       [ True,  True,  True]])

In [63]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [64]:
a1

array([1, 2, 3])

In [65]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

## Sorting array

In [66]:
random_array = np.random.randint(10, size=(3,5))


In [67]:
random_array

array([[2, 7, 1, 6, 3],
       [1, 2, 1, 8, 7],
       [5, 6, 6, 7, 5]])

In [69]:
random_array.shape

(3, 5)

In [70]:
np.sort(random_array)

array([[1, 2, 3, 6, 7],
       [1, 1, 2, 7, 8],
       [5, 5, 6, 6, 7]])

In [71]:
np.argsort(random_array)

array([[2, 0, 4, 3, 1],
       [0, 2, 1, 4, 3],
       [0, 4, 1, 2, 3]])

In [72]:
a1

array([1, 2, 3])

In [73]:
np.argsort(a1)

array([0, 1, 2])

In [78]:
np.argmin(a1)

0

In [79]:
np.argmax(random_array, axis=0) # this goes column wise i.e. max in each column

array([2, 0, 2, 1, 1])

In [77]:
np.argmax(random_array, axis=1) # this goes row wise, max in each row

array([1, 3, 3])

In [80]:
random_array

array([[2, 7, 1, 6, 3],
       [1, 2, 1, 8, 7],
       [5, 6, 6, 7, 5]])

## Practical Example

<img src="images/panda.png" />



In [83]:
# Turn an image into Numpy array

from matplotlib.image import imread

panda = imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [84]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [85]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [86]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="images/car-photo.png" />

In [88]:
car = imread("images/car-photo.png")
type(car)

numpy.ndarray