# Intro To Numpy

In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# numpy has type ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([
    [1, 2.0, 3.3],
    [4, 5, 6.5]
])

a3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])

a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a3.shape

(2, 3, 3)

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [11]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [13]:
# Create a datafrom from numpy array

import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating numpy arrays

In [14]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [15]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [19]:
random_array = np.random.randint(0, 100, size=(3, 5))
random_array

array([[40, 91, 48, 40, 81],
       [55, 83, 93, 16,  0],
       [15, 97, 39, 43, 13]])

In [20]:
random_array.size

15

In [21]:
random_array.shape

(3, 5)

In [22]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.16280765, 0.36864796, 0.27216947],
       [0.61056823, 0.7257284 , 0.62154325],
       [0.13824318, 0.13169821, 0.19204035],
       [0.525979  , 0.04655657, 0.22002373],
       [0.08309024, 0.19757331, 0.50872051]])

In [23]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.06358423, 0.66507012, 0.4162552 ],
       [0.65337944, 0.95878642, 0.27142763],
       [0.1937823 , 0.48087799, 0.99920497],
       [0.71096918, 0.50213877, 0.45005381],
       [0.3139503 , 0.77893324, 0.24844594]])

In [24]:
# Pseudo-random numbers
np.random.seed(100)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[8, 8, 3],
       [7, 7, 0],
       [4, 2, 5],
       [2, 2, 2],
       [1, 0, 8]])

## 3. Viewing arrays and matrices

In [26]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 7, 8])

In [27]:
a1

array([1, 2, 3])

In [28]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [29]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [30]:
a1[0]

1

In [31]:
a2[0]

array([1. , 2. , 3.3])

In [32]:
a2.shape

(2, 3)

In [33]:
a2[0].shape

(3,)

In [34]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a3[0].shape

(3, 3)

In [36]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [37]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))

In [38]:
a4

array([[[[4, 0, 9, 6, 2],
         [4, 1, 5, 3, 4],
         [4, 3, 7, 1, 1],
         [7, 7, 0, 2, 9]],

        [[9, 3, 2, 5, 8],
         [1, 0, 7, 6, 2],
         [0, 8, 2, 5, 1],
         [8, 1, 5, 4, 2]],

        [[8, 3, 5, 0, 9],
         [3, 6, 3, 4, 7],
         [6, 3, 9, 0, 4],
         [4, 5, 7, 6, 6]]],


       [[[2, 4, 2, 7, 1],
         [6, 6, 0, 7, 2],
         [3, 5, 4, 2, 4],
         [3, 7, 9, 0, 0]],

        [[5, 9, 6, 6, 5],
         [6, 4, 7, 3, 9],
         [2, 3, 8, 7, 1],
         [5, 9, 3, 0, 6]],

        [[2, 3, 4, 8, 9],
         [8, 5, 2, 7, 5],
         [9, 0, 9, 8, 6],
         [2, 0, 5, 3, 2]]]])

In [39]:
# Get the first four numbers of inner most array in a4
a4[:, :, :, :4]

array([[[[4, 0, 9, 6],
         [4, 1, 5, 3],
         [4, 3, 7, 1],
         [7, 7, 0, 2]],

        [[9, 3, 2, 5],
         [1, 0, 7, 6],
         [0, 8, 2, 5],
         [8, 1, 5, 4]],

        [[8, 3, 5, 0],
         [3, 6, 3, 4],
         [6, 3, 9, 0],
         [4, 5, 7, 6]]],


       [[[2, 4, 2, 7],
         [6, 6, 0, 7],
         [3, 5, 4, 2],
         [3, 7, 9, 0]],

        [[5, 9, 6, 6],
         [6, 4, 7, 3],
         [2, 3, 8, 7],
         [5, 9, 3, 0]],

        [[2, 3, 4, 8],
         [8, 5, 2, 7],
         [9, 0, 9, 8],
         [2, 0, 5, 3]]]])

## 4. Manipulating & Comparing arrays

### Arithmetic

In [40]:
a1

array([1, 2, 3])

In [41]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
ones = np.ones(3)

In [43]:
a1 + ones

array([2., 3., 4.])