In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndArray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([ [1, 2, 3.3], [4, 5, 6.5]])

a3 = np.array([
    [ [1, 2, 3], [4, 5, 6] ],
    [ [7, 8, 9], [10, 11, 12] ],
    [ [13, 14, 15], [16, 17, 18] ]
])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a1

array([1, 2, 3])

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(3, 2, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
# Create a dataframe from numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [24]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [25]:
sample_array.dtype

dtype('int64')

In [27]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
ones.dtype

dtype('float64')

In [29]:
zeroes = np.zeros((2, 3))

In [30]:
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
range_array = np.arange(0, 10, 2)

In [32]:
range_array

array([0, 2, 4, 6, 8])

In [35]:
random_array = np.random.randint(0, 10, size=(3, 5))

In [36]:
random_array

array([[7, 1, 7, 8, 2],
       [4, 9, 9, 7, 7],
       [4, 9, 3, 6, 3]])

In [37]:
random_array.size

15

In [38]:
random_array.shape

(3, 5)

In [39]:
np.random.random((5, 3))

array([[0.31224829, 0.64628176, 0.57964621],
       [0.43246676, 0.54776597, 0.70380529],
       [0.95369369, 0.29521737, 0.35734651],
       [0.22951507, 0.75195346, 0.69487596],
       [0.06506076, 0.04281627, 0.03153944]])

In [40]:
random_array_3 = np.random.rand(5, 3)

In [41]:
random_array_3

array([[0.43785114, 0.67810726, 0.42001228],
       [0.00876783, 0.67499569, 0.46067628],
       [0.85604068, 0.31621482, 0.83014027],
       [0.07472451, 0.9732925 , 0.03775072],
       [0.51472122, 0.95866543, 0.42785331]])

In [45]:
# Pseudo-random numbers
s = np.random.seed(0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])